### ISSUE TITLE
Celluloid running in backported mode

### ISSUE THREAD

**Issue by austinpray** [zaius/vagrant-listen-server#1]
When using this plugin I get

```
Celluloid 0.17.0 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
```

Whenever I `vagrant up`.

The plugin also fails with this error:

```
/Users/austinpray/.vagrant.d/gems/gems/celluloid-0.17.0/lib/celluloid/calls.rb:48:in `check': wrong number of arguments (2 for 1) (ArgumentError)
```

But I don't know if this is related.

**Comment by zaius** [comment]
Sorry for missing this - somehow notifications on my own repo were turned off...

Part of the reason I used listen / celluloid / etc. was because they should have already been installed as part of vagrant's gemspec. Though that might have changed. Which OS and version of vagrant are you using?

**Comment by austinpray** [comment]
Whoops! Forgot to include this very important information in the first place haha.

```
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]
OSX Yosemite 10.10.4
Vagrant 1.7.4
```

**Comment by zaius** [comment]
Need to dig into this a bit - I think the gemspec is installing the newest version of celluloid rather than relying on vagrant's version. And I think that's because vagrant relies on listen, and listen has removed celluloid as a dependency, which means I probably should too.

Will update here once I work it out. Thanks for the report!

**Comment by zaius** [comment]
Just pushed v0.0.5 - it supports the new version of listen, and drops the celluloid dependency for a stdlib thread based TCP server. The message format has changed slightly, because I have no clue what the format was beforehand, but the idea is the same.

I have only been running this for about 15 minutes now, so it's probably a bit buggy - let me know if you run into any issues.
